### ISSUE TITLE
Issue when eXo platform is behind an enterprise proxy which needs authentication

### ISSUE THREAD

**Issue by mcapitanio** [exo-addons/cloud-drive-extension#39]
Hi,

I am facing an issue when eXo platform (4.2.0) is behind a proxy which needs authentication.

If have already defined the options for proxy settings in "setenv-customize.bat" as follows:

SET "CATALINA_OPTS=%CATALINA_OPTS% -Dhttp.proxyHost=http://<MY_PROXY_IP> -Dhttp.proxyPort=<MY_PROXY_PORT> -Dhttp.proxyUser=<USER> -Dhttp.proxyPassword=<PWD>"

I get the following error stack trace when I try to "Connect Cloud Documents" (with a connect timed out error):

2015-08-13 07:25:06,169 | WARN  | Error authenticating user to access Google Drive [o.e.clouddrive.rest.ConnectService<http-nio-0.0.0.0-8080-exec-30>] 
org.exoplatform.clouddrive.gdrive.GoogleDriveException: Error authenticating user code: connect timed out
    at org.exoplatform.clouddrive.gdrive.GoogleDriveAPI.<init>(GoogleDriveAPI.java:431) ~[exo-clouddrive-gdrive-services-1.2.1.jar:1.2.1]
    at org.exoplatform.clouddrive.gdrive.GoogleDriveConnector$API.build(GoogleDriveConnector.java:96) ~[exo-clouddrive-gdrive-services-1.2.1.jar:1.2.1]
    at org.exoplatform.clouddrive.gdrive.GoogleDriveConnector.authenticate(GoogleDriveConnector.java:193) ~[exo-clouddrive-gdrive-services-1.2.1.jar:1.2.1]
    at org.exoplatform.clouddrive.gdrive.GoogleDriveConnector.authenticate(GoogleDriveConnector.java:47) ~[exo-clouddrive-gdrive-services-1.2.1.jar:1.2.1]
    at org.exoplatform.clouddrive.CloudDriveServiceImpl.authenticate(CloudDriveServiceImpl.java:271) ~[exo-clouddrive-services-core-1.2.1.jar:1.2.1]
    at org.exoplatform.clouddrive.rest.ConnectService.userAuth(ConnectService.java:716) ~[exo-clouddrive-services-core-1.2.1.jar:1.2.1]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
    at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker$1.run(DefaultMethodInvoker.java:194) ~[exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.commons.utils.SecurityHelper.doPrivilegedExceptionAction(SecurityHelper.java:310) ~[exo.kernel.commons-2.4.13-GA.jar:2.4.13-GA]
    at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:190) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.services.rest.impl.method.DefaultMethodInvoker.invokeMethod(DefaultMethodInvoker.java:183) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.services.rest.impl.RequestDispatcher.invokeSubResourceMethod(RequestDispatcher.java:657) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.services.rest.impl.RequestDispatcher.dispatch(RequestDispatcher.java:602) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.services.rest.impl.RequestDispatcher.dispatch(RequestDispatcher.java:507) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.services.rest.impl.RequestHandlerImpl.handleRequest(RequestHandlerImpl.java:146) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.services.rest.servlet.RestServlet.onService(RestServlet.java:85) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.exoplatform.container.web.AbstractHttpServlet.service(AbstractHttpServlet.java:132) [exo.kernel.container-2.4.13-GA.jar:2.4.13-GA]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:96) [exo.portal.component.web.api-4.2.0-PLF.jar:4.2.0-PLF]
    at org.exoplatform.platform.common.account.setup.web.AccountSetupFilter.doFilter(AccountSetupFilter.java:61) [platform-component-common-4.2.0.jar:4.2.0]
    at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.2.0-PLF.jar:4.2.0-PLF]
    at org.exoplatform.services.filters.sessionProvider.ThreadLocalACLSessionProviderInitializedFilter.doFilter(ThreadLocalACLSessionProviderInitializedFilter.java:45) [ecms-core-services-4.2.0.jar:4.2.0]
    at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.2.0-PLF.jar:4.2.0-PLF]
    at org.exoplatform.web.filter.ExtensibleFilter.doFilter(ExtensibleFilter.java:71) [exo.portal.component.web.api-4.2.0-PLF.jar:4.2.0-PLF]
    at org.exoplatform.web.filter.GenericFilter.doFilter(GenericFilter.java:70) [exo.portal.component.web.api-4.2.0-PLF.jar:4.2.0-PLF]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.services.rest.servlet.RestEncodingFilter.doFilter(RestEncodingFilter.java:58) [exo.ws.rest.core-2.3.13-GA.jar:2.3.13-GA]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.web.CacheUserProfileFilter.doFilter(CacheUserProfileFilter.java:72) [exo.portal.component.web.security-4.2.0-PLF.jar:4.2.0-PLF]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.frameworks.jcr.web.ThreadLocalSessionProviderInitializedFilter.doFilter(ThreadLocalSessionProviderInitializedFilter.java:122) [exo.jcr.framework.web-1.15.13-GA.jar:1.15.13-GA]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.web.login.ConversationStateUpdateFilter.doFilter(ConversationStateUpdateFilter.java:66) [exo.portal.component.web.security-4.2.0-PLF.jar:4.2.0-PLF]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.services.security.web.SetCurrentIdentityFilter.doFilter(SetCurrentIdentityFilter.java:88) [exo.core.component.security.core-2.5.13-GA.jar:2.5.13-GA]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.web.login.RememberMeFilter.doFilter(RememberMeFilter.java:81) [exo.portal.component.web.security-4.2.0-PLF.jar:4.2.0-PLF]
    at org.exoplatform.web.login.RememberMeFilter.doFilter(RememberMeFilter.java:49) [exo.portal.component.web.security-4.2.0-PLF.jar:4.2.0-PLF]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.gatein.sso.integration.SSODelegateFilter.doFilter(SSODelegateFilter.java:60) [sso-integration-1.3.1.Final.jar:1.3.1.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.exoplatform.container.web.PortalContainerFilter.doFilter(PortalContainerFilter.java:78) [exo.kernel.container-2.4.13-GA.jar:2.4.13-GA]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.55]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.55]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:7.0.55]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.55]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.55]
    at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:358) [catalina.jar:7.0.55]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.55]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.55]
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.55]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.55]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) [tomcat-coyote.jar:7.0.55]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695) [tomcat-coyote.jar:7.0.55]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.55]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method) ~[na:1.7.0_79]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339) ~[na:1.7.0_79]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200) ~[na:1.7.0_79]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182) ~[na:1.7.0_79]
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.7.0_79]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
    at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625) ~[na:1.7.0_79]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.7.0_79]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_79]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_79]
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[na:1.7.0_79]
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[na:1.7.0_79]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.7.0_79]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933) ~[na:1.7.0_79]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.7.0_79]
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1092) ~[na:1.7.0_79]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[na:1.7.0_79]
    at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77) ~[google-http-client-1.18.0-rc.jar:1.18.0-rc]
    at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965) ~[google-http-client-1.18.0-rc.jar:1.18.0-rc]
    at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283) ~[google-oauth-client-1.18.0-rc.jar:1.18.0-rc]
    at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158) ~[google-api-client-1.18.0-rc.jar:1.18.0-rc]
    at org.exoplatform.clouddrive.gdrive.GoogleDriveAPI.<init>(GoogleDriveAPI.java:429) ~[exo-clouddrive-gdrive-services-1.2.1.jar:1.2.1]
    ... 75 common frames omitted

**Comment by pnedonosko** [comment]
I'm not sure it's correct settings "-Dhttp.proxyHost=http:// -Dhttp.proxyPort= -Dhttp.proxyUser= -Dhttp.proxyPassword=". Only if you haven't omitted real values. Have you?

**Comment by mcapitanio** [comment]
Hi,

yes, I have obfuscated real value, I mean, this is what I have used:


SET "CATALINA_OPTS=%CATALINA_OPTS% -Dhttp.proxyHost=http://10.100.11.11
-Dhttp.proxyPort=80 -Dhttp.proxyUser=mcapitanio
-Dhttp.proxyPassword=sdkqewi"

Kind regards,
Matteo Capitanio


2015-08-14 10:35 GMT+02:00 Peter Nedonosko <notifications@github.com>:

**Comment by pnedonosko** [comment]
Is this issue still actual?
