### ISSUE TITLE
A 404 error occur when accessing to my documents pages

### ISSUE THREAD

**Issue by LamiaBouhajja** [exo-addons/cloud-drive-extension#66]
There is a 404 error when i try to access to my documents page, caused by "cloudDrive.init" function.

here is errors i get : 

jquery-min.js:161 GET https://community-dev.exoplatform.com/portal/rest/clouddrive/drive?workspace=collaboration&path=%2Fsites 404 ()
send	@	jquery-min.js:161
ajax	@	jquery-min.js:156
O	@	cloudDriveGRP-min.js:50
g	@	cloudDriveGRP-min.js:59
initContext	@	cloudDriveGRP-min.js:69
init	@	cloudDriveGRP-min.js:68
(anonymous)	@	siteExplorer:3784
execCb	@	bootstrap-min.js:27
check	@	bootstrap-min.js:18
(anonymous)	@	bootstrap-min.js:16
(anonymous)	@	bootstrap-min.js:6
(anonymous)	@	bootstrap-min.js:22
h	@	bootstrap-min.js:6
emit	@	bootstrap-min.js:22
check	@	bootstrap-min.js:19
(anonymous)	@	bootstrap-min.js:16
(anonymous)	@	bootstrap-min.js:6
(anonymous)	@	bootstrap-min.js:22
h	@	bootstrap-min.js:6
emit	@	bootstrap-min.js:22
check	@	bootstrap-min.js:19
enable	@	bootstrap-min.js:21
init	@	bootstrap-min.js:16
Z	@	bootstrap-min.js:14
completeLoad	@	bootstrap-min.js:25
onScriptLoad	@	bootstrap-min.js:27

**Comment by pnedonosko** [comment]
In general 404 doesn't mean anything evil or buggy in this case. It only tells what it mean: a resource (connected drive) not found, and so, if it happens not for already connected drive it is normal.
To clarify describe your usecase when/where it happens and steps and/or screens of the effect.

**Comment by LamiaBouhajja** [comment]
In JavaScript, an error can block all functions executed after. Currentrly, in document pages we are not able to open sub menu, which is a java script action in our product.

Attachements: 
![1](https://user-images.githubusercontent.com/21038721/31657794-3ffc80fc-b327-11e7-9e12-8ba471ac5f4c.PNG)
![2](https://user-images.githubusercontent.com/21038721/31657795-401c2db2-b327-11e7-8e20-9964b7b4b5bb.png)

**Comment by LamiaBouhajja** [comment]
There is a related Log : 

2017-10-17 11:57:08,241 | ERROR | Error reading drive collaboration:/Users/k___/kr___/kro___/krout_medamine/Private/Google Drive - mkroutexoplatform.com [o.e.clouddrive.rest.DriveService<http-nio-127.0.0.1-10180-exec-11>] 
java.lang.NullPointerException: null 
at org.exoplatform.clouddrive.gdrive.GoogleDriveAPI$AuthToken.onTokenErrorResponse(GoogleDriveAPI.java:309) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0] 
at org.exoplatform.shaded.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:507) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0] 
at org.exoplatform.clouddrive.gdrive.GoogleDriveAPI.refreshAccess(GoogleDriveAPI.java:1278) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0] 
at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive.refreshAccess(JCRLocalGoogleDrive.java:1396) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0] 
at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive.synchronize(JCRLocalCloudDrive.java:3991) ~[exo-clouddrive-services-core-1.5.0.jar:1.5.0] 
at org.exoplatform.clouddrive.rest.DriveService.readDrive(DriveService.java:177) ~[exo-clouddrive-services-core-1.5.0.jar:1.5.0] 
at org.exoplatform.clouddrive.rest.DriveService.synchronize(DriveService.java:149) ~[exo-clouddrive-services-core-1.5.0.jar:1.5.0]

**Comment by mkrout** [comment]
We Got this stacktrace:
2017-10-17 11:57:08,241 | ERROR | Error reading drive collaboration:/Users/k___/kr___/kro___/krout_medamine/Private/Google Drive - mkroutexoplatform.com [o.e.clouddrive.rest.DriveService<http-nio-127.0.0.1-10180-exec-11>] 
java.lang.NullPointerException: null
	at org.exoplatform.clouddrive.gdrive.GoogleDriveAPI$AuthToken.onTokenErrorResponse(GoogleDriveAPI.java:309) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0]
	at org.exoplatform.shaded.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:507) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0]
	at org.exoplatform.clouddrive.gdrive.GoogleDriveAPI.refreshAccess(GoogleDriveAPI.java:1278) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0]
	at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive.refreshAccess(JCRLocalGoogleDrive.java:1396) ~[exo-clouddrive-gdrive-services-1.5.0.jar:1.5.0]
	at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive.synchronize(JCRLocalCloudDrive.java:3991) ~[exo-clouddrive-services-core-1.5.0.jar:1.5.0]
	at org.exoplatform.clouddrive.rest.DriveService.readDrive(DriveService.java:177) ~[exo-clouddrive-services-core-1.5.0.jar:1.5.0]
	at org.exoplatform.clouddrive.rest.DriveService.synchronize(DriveService.java:149) ~[exo-clouddrive-services-core-1.5.0.jar:1.5.0]

**Comment by pnedonosko** [comment]
A 404 isn't a problem itself. A case where NPE caught in the logic: it will be a message in the server log - it was fixed in 1.6.0-M01.
