### ISSUE TITLE
JCR constraint violation during Google Drive synchronization

### ISSUE THREAD

**Issue by vsellier** [exo-addons/cloud-drive-extension#70]
The synchronization is failing with the following error when I try to synchronize my google drive content (the jcr path is obfuscated but the length is respected):
```
2018-03-06 15:20:30,999 | ERROR | Google Drive - xxxxx@xxxxx.com connect failed. [o.e.clouddrive.rest.ConnectService<clouddrive-thread-2>]
javax.jcr.nodetype.ConstraintViolationException: Mandatory item org.exoplatform.services.jcr.datamodel.InternalQName@c569a118 ([http://www.exoplatform.com/jcr/clouddrive/1.0/]lastUser) not found. Node [[]:1[]Users:1[]x___:1[]xx___:1[]xxx___:1[]username:1[]Private:1[]Google Drive - useremail.com:1[]Dep QA:1[]XXXX XXXXXXXX:1[]5.0.x:1[]XXX:1[]Benchmark:1[]X_XX-X.X.X:1[]Xxxxx Xxxxxx Xxxxxxxxxxx template:1 primary type: [http://www.jcp.org/jcr/nt/1.0]file]
        at org.exoplatform.services.jcr.impl.core.SessionDataManager.validateMandatoryChildren(SessionDataManager.java:1834) ~[exo.jcr.component.core-5.0.0-RC11.jar:5.0.0-RC11]
        at org.exoplatform.services.jcr.impl.core.SessionDataManager.validateMandatoryItem(SessionDataManager.java:1802) ~[exo.jcr.component.core-5.0.0-RC11.jar:5.0.0-RC11]
        at org.exoplatform.services.jcr.impl.core.SessionDataManager.validate(SessionDataManager.java:1670) ~[exo.jcr.component.core-5.0.0-RC11.jar:5.0.0-RC11]
        at org.exoplatform.services.jcr.impl.core.SessionDataManager.commit(SessionDataManager.java:1556) ~[exo.jcr.component.core-5.0.0-RC11.jar:5.0.0-RC11]
        at org.exoplatform.services.jcr.impl.core.ItemImpl.save(ItemImpl.java:706) ~[exo.jcr.component.core-5.0.0-RC11.jar:5.0.0-RC11]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$AbstractCommand.save(JCRLocalCloudDrive.java:1070) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$AbstractCommand.saveChunk(JCRLocalCloudDrive.java:1085) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$AbstractCommand.addChanged(JCRLocalCloudDrive.java:1102) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$ConnectCommand.addConnected(JCRLocalCloudDrive.java:1495) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:202) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchChilds(JCRLocalGoogleDrive.java:159) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.gdrive.JCRLocalGoogleDrive$Connect.fetchFiles(JCRLocalGoogleDrive.java:102) ~[exo-clouddrive-gdrive-services-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$ConnectCommand.process(JCRLocalCloudDrive.java:1548) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$AbstractCommand.exec(JCRLocalCloudDrive.java:1241) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$CommandCallable.call(JCRLocalCloudDrive.java:868) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at org.exoplatform.clouddrive.jcr.JCRLocalCloudDrive$CommandCallable.call(JCRLocalCloudDrive.java:848) ~[exo-clouddrive-services-core-1.6.0-M01.jar:1.6.0-M01]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

**Comment by t4bbo** [comment]
Same issue here. Any fixes yet?

**Comment by pnedonosko** [comment]
Hi, it's already in the backlog and will be worked for a next version.

**Comment by t4bbo** [comment]
how far is the process so far?

**Comment by pnedonosko** [comment]
It should be fixed for Platform 4.4 (Cloud Drive 1.5.1). Version for Platform 5.0 will come soon.

**Comment by t4bbo** [comment]
very nice! Do you know how long it will take to fix it for 5.0? because were working with 5.0 ;)

**Comment by pnedonosko** [comment]
Version for Platform 5.0 will come in about two weeks. Indeed, in meantime you can use the latest state by installing a 1.6.x-SNAPSHOT version. Use following command to install the snapshot in your Platform 5.0.

```
./addon install --snapshots exo-cloud-drive:1.6.x-SNAPSHOT
```

**Comment by pnedonosko** [comment]
Should be fixed in version 1.6.0.

**Comment by t4bbo** [comment]
Can we reopen this issue because is still can not get this to work?
Error is now: `Authentication not initiated or expired. Try again later.`
After the complete login and permission procedure is run through.
Maybe there is another issue there regarding the token sent to dropbox and gdrive (those are the only one i tried it with)
best Philipp

**Comment by pnedonosko** [comment]
It's definitely not "JCR constraint violation" as this issue tells. @t4bbo please open a new issue and add all details you have, including server log and the browser console, screenshots, and request details if possible (of beginning of the connect process to `/clouddrive/connect/init/$provider_id` and a redirect to `/clouddrive/connect/$provider_id` after the authentication in Google/Dropbox - you can do this in Chrome Dev tools). 
According the error message you may have on of the following: authentication in Google happens longer of 5sec (it should not in general, but if user spent more time he/she can retry and it will work); your browser cleans the cookies set by first init request (then you need fix this in the browser); you run a cluster of eXo Platform servers (and then you need configure it to server the same user by single server for this kind of resources).
